# Generated by Django 5.2.17 on 2026-09-02 11:48

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.CharField(max_length=190, unique=True)),
                ('country_code', models.CharField(max_length=2)),
                ('industry', models.CharField(blank=True, max_length=120, null=True)),
                ('default_currency', models.CharField(max_length=3)),
                ('timezone', models.CharField(max_length=64)),
                ('fiscal_year_start', models.DateField(blank=True, null=True)),
                ('working_week', models.CharField(default='Mon-Fri', max_length=20)),
                ('default_language', models.CharField(default='en', max_length=20)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('plan_code', models.CharField(default='beta_free', max_length=50)),
                ('status', models.CharField(default='active', max_length=30)),
                ('trial_user_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ai_credit_balance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country_code', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('attendance_radius_m', models.PositiveIntegerField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('wfh_monthly_cap', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'offices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('parent_department_id', models.BigIntegerField(blank=True, null=True)),
                ('head_employee_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(blank=True, db_column='office_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.office')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'departments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrganizationObjective',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, null=True)),
                ('weightage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'organization_objectives',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrganizationSetting',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_mode', models.CharField(default='global', max_length=30)),
                ('exit_clearance_mode', models.CharField(default='strict', max_length=30)),
                ('free_tier_employee_limit', models.PositiveIntegerField(default=20)),
                ('low_ai_credit_threshold', models.PositiveIntegerField(default=50)),
                ('seed_data_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organization.organization')),
            ],
            options={
                'db_table': 'organization_settings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('lead_employee_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='organization.department')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'teams',
                'managed': True,
            },
        ),
    ]
