# Generated by Django 5.2.17 on 2026-09-02 11:48

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('grade', models.CharField(blank=True, max_length=40, null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'designations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentExpiryReminder',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_document_id', models.BigIntegerField()),
                ('days_before', models.PositiveIntegerField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'document_expiry_reminders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_id', models.BigIntegerField(blank=True, null=True)),
                ('leave_policy_id', models.BigIntegerField(blank=True, null=True)),
                ('employee_code', models.CharField(max_length=80)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.CharField(max_length=190)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=30, null=True)),
                ('nationality', models.CharField(blank=True, max_length=60, null=True)),
                ('national_id_no', models.CharField(blank=True, max_length=80, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=80, null=True)),
                ('designation_text', models.CharField(blank=True, db_column='designation', max_length=120, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=60, null=True)),
                ('employment_status', models.CharField(default='active', max_length=40)),
                ('hire_date', models.DateField()),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_designation', models.ForeignKey(blank=True, db_column='designation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='people.designation')),
                ('department', models.ForeignKey(blank=True, db_column='department_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organization.department')),
                ('office', models.ForeignKey(blank=True, db_column='office_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organization.office')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('reporting_manager', models.ForeignKey(blank=True, db_column='reporting_manager_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='direct_reports', to='people.employee')),
                ('team', models.ForeignKey(blank=True, db_column='team_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organization.team')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
                'managed': True,
                'unique_together': {('organization', 'email'), ('organization', 'employee_code')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeBankAccount',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=120)),
                ('account_title', models.CharField(max_length=160)),
                ('account_number', models.CharField(max_length=80)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=30, null=True)),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='people.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'employee_bank_accounts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=80)),
                ('document_number', models.CharField(blank=True, max_length=120, null=True)),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='valid', max_length=30)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='people.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'employee_documents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=120)),
                ('institution', models.CharField(max_length=180)),
                ('field_of_study', models.CharField(blank=True, max_length=120, null=True)),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=40, null=True)),
                ('certificate_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='education', to='people.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'employee_education',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeEmergencyContact',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('relationship', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=190, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='people.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'employee_emergency_contacts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkExperience',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=180)),
                ('job_title', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='people.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'employee_work_experience',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProbationReview',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probation_end_date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=30)),
                ('extended_to_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='people.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'probation_reviews',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeReportingManager',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='people.employee')),
                ('manager_employee', models.ForeignKey(db_column='manager_employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='people.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'employee_reporting_managers',
                'managed': True,
                'unique_together': {('employee', 'manager_employee')},
            },
        ),
    ]
