# Generated by Django 5.2.17 on 2026-09-03 06:13

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPricing',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plan_pricing',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SurveyCampaign',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('channel', models.CharField(default='google_forms', max_length=40)),
                ('target_min', models.PositiveIntegerField(default=20)),
                ('target_max', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'survey_campaigns',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccountingIntegration',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=60)),
                ('endpoint_url', models.CharField(max_length=255)),
                ('auth_type', models.CharField(default='bearer', max_length=40)),
                ('secret_ref', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'accounting_integrations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccountingIntegrationMapping',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrms_component', models.CharField(max_length=120)),
                ('ledger_account_code', models.CharField(max_length=80)),
                ('ledger_account_name', models.CharField(blank=True, max_length=180, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'accounting_integration_mappings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_role', models.CharField(blank=True, max_length=120, null=True)),
                ('industry', models.CharField(blank=True, max_length=120, null=True)),
                ('answers_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey_campaign', models.ForeignKey(db_column='survey_campaign_id', on_delete=django.db.models.deletion.CASCADE, to='platform_admin.surveycampaign')),
            ],
            options={
                'db_table': 'survey_responses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('billing_period', models.CharField(max_length=20)),
                ('plan_code', models.CharField(max_length=50)),
                ('active_employee_count', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(default='generated', max_length=30)),
                ('generated_at', models.DateTimeField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'billing_records',
                'managed': True,
                'unique_together': {('organization', 'billing_period')},
            },
        ),
    ]
