# Generated by Django 5.2.17 on 2026-09-03 06:03

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateStageLabel',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_label', models.CharField(max_length=120)),
                ('external_label', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'candidate_stage_labels',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('job_description', models.TextField()),
                ('skills_text', models.TextField(blank=True, null=True)),
                ('openings', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department')),
                ('office', models.ForeignKey(blank=True, db_column='office_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.office')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'job_postings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.CharField(max_length=190)),
                ('phone', models.CharField(blank=True, max_length=60, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(default='portal', max_length=40)),
                ('cv_url', models.CharField(blank=True, max_length=500, null=True)),
                ('profile_json', models.JSONField(blank=True, null=True)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_rating', models.CharField(blank=True, max_length=30, null=True)),
                ('stage', models.CharField(default='applied', max_length=60)),
                ('candidate_visible_stage', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('job_posting', models.ForeignKey(db_column='job_posting_id', on_delete=django.db.models.deletion.CASCADE, to='recruitment.jobposting')),
            ],
            options={
                'db_table': 'candidates',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CandidateAccount',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=190)),
                ('full_name', models.CharField(blank=True, max_length=160, null=True)),
                ('linkedin_sub', models.CharField(blank=True, max_length=120, null=True)),
                ('magic_token', models.CharField(blank=True, max_length=120, null=True)),
                ('magic_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'candidate_accounts',
                'managed': True,
                'unique_together': {('organization', 'email')},
            },
        ),
    ]
