# Generated by Django 5.2.17 on 2026-09-03 06:08

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitClearanceTask',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_workflow_id', models.BigIntegerField(blank=True, null=True)),
                ('department_name', models.CharField(max_length=80)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='people.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'exit_clearance_tasks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExitWorkflow',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_type', models.CharField(blank=True, max_length=255, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('short_notice_recovery', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('leave_encashment', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gratuity_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('loan_recovery', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('final_settlement_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('clearance_override', models.BooleanField(default=False)),
                ('clearance_override_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.employee')),
            ],
            options={
                'db_table': 'exit_workflows',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExitSettlement',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outstanding_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('leave_encashment', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gratuity_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('loan_recovery', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_settlement', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='people.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('exit_workflow', models.ForeignKey(db_column='exit_workflow_id', on_delete=django.db.models.deletion.CASCADE, to='exit_mgmt.exitworkflow')),
            ],
            options={
                'db_table': 'exit_settlements',
                'managed': True,
                'unique_together': {('organization', 'exit_workflow', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='OrgClearanceDepartment',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=80)),
                ('responsible_user_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'org_clearance_departments',
                'managed': True,
                'unique_together': {('organization', 'department_name')},
            },
        ),
    ]
