# Generated by Django 5.2.17 on 2026-09-03 06:08

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('performance_cycle_id', models.BigIntegerField(blank=True, null=True)),
                ('organization_objective_id', models.BigIntegerField(blank=True, null=True)),
                ('employee_id', models.BigIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team'), ('organizational', 'Organizational')], default='individual', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('achieved_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weightage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'goals',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PerformanceCycle',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('cycle_type', models.CharField(choices=[('annual', 'Annual'), ('semi_annual', 'Semi-Annual'), ('quarterly', 'Quarterly'), ('custom', 'Custom')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'performance_cycles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PromotionRequest',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_designation', models.CharField(max_length=120)),
                ('salary_structure_id', models.BigIntegerField(blank=True, null=True)),
                ('effective_date', models.DateField()),
                ('justification', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='people.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'promotion_requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PromotionApproval',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_no', models.PositiveIntegerField()),
                ('role_name', models.CharField(max_length=80)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('acted_by_user_id', models.BigIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('promotion_request', models.ForeignKey(db_column='promotion_request_id', on_delete=django.db.models.deletion.CASCADE, to='performance.promotionrequest')),
            ],
            options={
                'db_table': 'promotion_approvals',
                'managed': True,
            },
        ),
    ]
