# Generated by Django 5.2.17 on 2026-09-02 12:08

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('holiday_date', models.DateField()),
                ('holiday_type', models.CharField(default='public', max_length=40)),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(blank=True, db_column='office_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.office')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'holidays',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('pro_rata', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('previous_policy', models.ForeignKey(blank=True, db_column='previous_policy_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_policy_set', to='leave.leavepolicy')),
            ],
            options={
                'db_table': 'leave_policies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('duration_type', models.CharField(default='full_day', max_length=20)),
                ('requested_days', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('current_approval_level', models.PositiveIntegerField(default=1)),
                ('reason', models.TextField(blank=True, null=True)),
                ('applied_by_user_id', models.BigIntegerField(blank=True, null=True)),
                ('approved_by_user_id', models.BigIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('delegated_to_user_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='people.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'leave_requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_no', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=30)),
                ('acted_by_user_id', models.BigIntegerField(blank=True, null=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver_employee', models.ForeignKey(db_column='approver_employee_id', on_delete=django.db.models.deletion.CASCADE, to='people.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('leave_request', models.ForeignKey(db_column='leave_request_id', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='leave.leaverequest')),
            ],
            options={
                'db_table': 'leave_approvals',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, choices=[('annual', 'Annual'), ('casual', 'Casual'), ('sick', 'Sick'), ('maternal', 'Maternal'), ('paternal', 'Paternal'), ('self_managed', 'Self Managed')], max_length=20, null=True)),
                ('affects_balance', models.BooleanField(default=True)),
                ('annual_quota', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carry_forward_enabled', models.BooleanField(default=False)),
                ('carry_forward_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('carry_reset_date', models.DateField(blank=True, null=True)),
                ('encashable', models.BooleanField(default=False)),
                ('negative_balance_allowed', models.BooleanField(default=False)),
                ('auto_approve_threshold_days', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('policy', models.ForeignKey(blank=True, db_column='leave_policy_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_types', to='leave.leavepolicy')),
            ],
            options={
                'db_table': 'leave_types',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(db_column='leave_type_id', on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype'),
        ),
        migrations.CreateModel(
            name='LeaveApprovalTier',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_no', models.PositiveIntegerField()),
                ('role_name', models.CharField(max_length=120)),
                ('can_delegate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('leave_type', models.ForeignKey(blank=True, db_column='leave_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.leavetype')),
            ],
            options={
                'db_table': 'leave_approval_tiers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LeaveCarryForward',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type_category', models.CharField(max_length=30)),
                ('remaining_days', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carried_forward_days', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by_user_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='people.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('from_policy', models.ForeignKey(db_column='from_policy_id', on_delete=django.db.models.deletion.CASCADE, related_name='carry_forwards_from', to='leave.leavepolicy')),
                ('to_policy', models.ForeignKey(db_column='to_policy_id', on_delete=django.db.models.deletion.CASCADE, related_name='carry_forwards_to', to='leave.leavepolicy')),
            ],
            options={
                'db_table': 'leave_carry_forwards',
                'managed': True,
                'unique_together': {('employee', 'from_policy', 'to_policy', 'leave_type_category')},
            },
        ),
    ]
