# Generated by Django 5.2.17 on 2026-09-02 11:56

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('is_default', models.BooleanField(default=False)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'salary_structures',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=120)),
                ('component_type', models.CharField(max_length=30)),
                ('tax_treatment', models.CharField(default='taxable', max_length=30)),
                ('calc_method', models.CharField(default='fixed', max_length=30)),
                ('formula', models.TextField(blank=True, null=True)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('salary_structure', models.ForeignKey(db_column='salary_structure_id', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.salarystructure')),
            ],
            options={
                'db_table': 'salary_components',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompensation',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designation', models.ForeignKey(blank=True, db_column='designation_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.designation')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='people.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('salary_structure', models.ForeignKey(blank=True, db_column='salary_structure_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.salarystructure')),
            ],
            options={
                'db_table': 'employee_compensations',
                'managed': True,
            },
        ),
    ]
