# Generated by Django 5.2.17 on 2026-09-03 05:58

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('payroll', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLoan',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monthly_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='people.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'employee_loans',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExpenseReimbursement',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(default='other', max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('expense_date', models.DateField()),
                ('receipt_url', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('approved_by_user_id', models.BigIntegerField(blank=True, null=True)),
                ('payroll_run_id', models.BigIntegerField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='people.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'expense_reimbursements',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('payroll_scope', models.CharField(default='organization', max_length=40)),
                ('office_id', models.BigIntegerField(blank=True, null=True)),
                ('department_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('locked_by_user_id', models.BigIntegerField(blank=True, null=True)),
                ('approved_by_user_id', models.BigIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'payroll_runs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=120)),
                ('component_type', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='people.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('payroll_run', models.ForeignKey(db_column='payroll_run_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payrollrun')),
            ],
            options={
                'db_table': 'payroll_items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('rule_name', models.CharField(max_length=140)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'tax_rules',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', apps.core.fields.UnsignedBigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_min', models.DecimalField(decimal_places=2, max_digits=16)),
                ('range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('percentage_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_rule', models.ForeignKey(db_column='tax_rule_id', on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='payroll.taxrule')),
            ],
            options={
                'db_table': 'tax_brackets',
                'managed': True,
            },
        ),
    ]
